# Generated by Django 3.1.7 on 2021-05-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0002_auto_20210429_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePointConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('position', models.TextField(blank=True, null=True)),
                ('phase_rotation', models.CharField(choices=[('RST', 'RST'), ('STR', 'STR'), ('TRS', 'TRS'), ('RTS', 'RTS'), ('SRT', 'SRT'), ('TSR', 'TSR')], default='RST', max_length=3)),
                ('installation_date', models.DateTimeField()),
                ('max_current', models.FloatField(default=16.0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('socket_type', models.CharField(choices=[('TYP1', 'Typ_1'), ('TYP2', 'Typ_2'), ('CCS', 'CCS')], default='TYP2', max_length=4)),
                ('max_current', models.FloatField(default=16.0, max_length=6)),
                ('set_power_limit', models.IntegerField(default=11000)),
                ('phase_rotation', models.CharField(choices=[('RST', 'RST'), ('STR', 'STR'), ('TRS', 'TRS'), ('RTS', 'RTS'), ('SRT', 'SRT'), ('TSR', 'TSR')], default='RST', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='max_power',
            field=models.IntegerField(default=11000),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='protocol',
            field=models.CharField(choices=[('OCPP16_J', 'OCPP_1.6_JSON'), ('OCPP20_J', 'OCPP_2.0_JSON'), ('OCPP201_J', 'OCPP_2.0.1_JSON')], default='OCPP16_J', max_length=10),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='AccessRight',
        ),
        migrations.AddField(
            model_name='connector',
            name='charge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp_handler.chargepoint'),
        ),
        migrations.AddField(
            model_name='chargepointconfiguration',
            name='charge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp_handler.chargepoint'),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='charging_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cp_handler.chargingstation'),
            preserve_default=False,
        ),
    ]
