# Generated by Django 3.2.2 on 2021-05-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0003_auto_20210504_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(default='0000000000000000', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='chargepointconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='IdTagInfo',
            fields=[
                ('id_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cp_handler.idtag')),
                ('expiry_date', models.DateTimeField()),
                ('parent_id_tag', models.CharField(default='AAAAAAAAAAAAAAAA', max_length=20)),
                ('status', models.CharField(choices=[('ACCAPTED', 'accapted'), ('BLOCKED', 'blocked'), ('CONCURRENT', 'concurrent_tx'), ('EXPIRED', 'expired'), ('INVALID', 'invalid')], default='ACCAPTED', max_length=15)),
            ],
        ),
    ]
