# Generated by Django 3.2.2 on 2021-05-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0004_auto_20210512_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtaginfo',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
