# Generated by Django 3.2.2 on 2021-05-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0005_alter_idtaginfo_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtaginfo',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
