# Generated by Django 3.2.2 on 2021-05-13 11:29

from django.db import migrations, models
import ocpp_d.v16.enums


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0006_alter_idtaginfo_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtaginfo',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('concurrent_tx', 'ConcurrentTx')], default=ocpp_d.v16.enums.AuthorizationStatus['accepted'], max_length=32),
        ),
    ]
