# Generated by Django 3.2.2 on 2021-05-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0008_auto_20210514_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargepoint',
            old_name='chargePointModel',
            new_name='charge_point_model',
        ),
        migrations.RenameField(
            model_name='chargepoint',
            old_name='chargePointVendor',
            new_name='charge_point_vendor',
        ),
    ]
