# Generated by Django 3.2.2 on 2021-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0009_auto_20210514_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
