# Generated by Django 3.2.2 on 2021-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0010_alter_chargepoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
