# Generated by Django 3.2.2 on 2021-05-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0011_alter_chargepoint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_point_id', models.IntegerField(default=0)),
                ('connector_id', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('stop_time', models.DateTimeField(null=True)),
                ('start_meter_value', models.FloatField(blank=True)),
                ('stop_meter_value', models.FloatField(blank=True)),
                ('energy_consumed', models.FloatField(blank=True)),
                ('start_id_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_id', to='cp_handler.idtag')),
                ('stop_id_tag', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_id', to='cp_handler.idtag')),
            ],
        ),
    ]
