# Generated by Django 3.2.2 on 2021-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtag',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
