# Generated by Django 3.1.7 on 2021-05-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owns_charging_station', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricVehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=256)),
                ('capacity', models.IntegerField()),
                ('max_current', models.FloatField(default=16.0, max_length=6)),
                ('min_current', models.FloatField(default=16.0, max_length=6)),
                ('set_power_limit', models.IntegerField(default=11000)),
                ('soc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('electric_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.electricvehicle')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
            ],
        ),
    ]
