# Generated by Django 3.1.7 on 2021-05-04 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessright',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2021, 6, 28)),
        ),
        migrations.AddField(
            model_name='accessright',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.useraccount'),
        ),
    ]
