# Generated by Django 3.2.2 on 2021-05-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0004_auto_20210512_2229'),
        ('user', '0002_auto_20210504_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessright',
            name='charge_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cp_handler.chargepoint'),
        ),
    ]
