# Generated by Django 3.2.2 on 2021-05-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_handler', '0012_transaction'),
        ('user', '0003_accessright_charge_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=8)),
                ('zip_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cp_handler.idtag'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
